server:
  servlet:
    encoding:
      force-response: true

spring:
  profiles:
    include:
      - infra

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

# p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true

mybatis:
  type-aliases-package: com.hansol.hrm.service   # xml파일 result type에 패키지명을 생략할 수 있도록 alias 설정
  mapper-locations: mapper/**/*.xml # Mybatis mapper 위치 설정
  configuration:
    map-underscore-to-camel-case: true


